/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/


#include "DIALOG.h"
#include <stdint.h>
#include "startup_screen.h"
#include "WindowDLG.h"
#include "main.h"
#include "ff.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)



/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

 WM_HWIN startup_screen;
uint8_t user_select;

user_acc_t user_db[3] = {
		{0, 1},		//User 1 access: PROJECTOR
		{1, 1},		//User 2 access: FULL
		{1, 0}		//User 3 access: AC
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate_start[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 1, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 112, 47, 260, 73, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "USER 1", ID_BUTTON_0, 70, 138, 80, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "USER 2", ID_BUTTON_1, 200, 138, 80, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "USER 3", ID_BUTTON_2, 330, 138, 80, 80, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog_start(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00F0000F));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "HomeControl");
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'USER 1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
    	  user_select = check_user_access(0, user_db);
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'USER 2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
    	  user_select = check_user_access(1, user_db);
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'USER 3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
    	  user_select = check_user_access(2, user_db);
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
uint8_t check_user_access(uint8_t select, user_acc_t user_db[3])
{
	uint8_t user_index;
	if (user_db[select].ac_access == 1) {
		if (user_db[select].proj_access == 1) {
			user_index = 1; 		//full access
		} else {
			user_index = 2;			//AC access
		}
	} else if (user_db[select].proj_access == 1) {
		user_index = 3;				//projector access
	}
	  return user_index;
}


/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_start(void) {
  startup_screen = GUI_CreateDialogBox(_aDialogCreate_start, GUI_COUNTOF(_aDialogCreate_start), _cbDialog_start, WM_HBKWIN, 0, 0);
  return startup_screen;
}


/*************************** End of file ****************************/
